name: quds_server
description: A core server for creating fast dart servers with support of routers, controllers, middlewares.
version: 1.0.1+1
homepage: https://github.com/MohammedAsaadAsaad/quds_server

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  args: ^2.3.0
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.3.2
  dart_spawner: ^1.0.5
  dio: ^4.0.6
  hotreloader: ^3.0.1
  http: ^0.13.4
  logging: ^1.0.2
  project_template: ^1.0.2
  redis: ^2.0.0
  reflection_factory: ^1.0.13
  resource_portable: ^3.0.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  uuid: ^3.0.5
  validators: ^3.0.0
  yaml: ^3.1.0
  yaml_writer: ^1.0.1


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  
